<?php
namespace llgc\src;

class csvTemplate {

  public function csvHeader()
  {
    return array(
      array(
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33'
      ),
      
      array(
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ),
      
      array(
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ),
      
      
      array(
        'Image Identifier',
        'Parent ID*',
        'Page Order*',
        'Image/File Name',
        'Title EN',
        'Title CY',
        'Description EN',
        'Description CY',
        'Item type',
        'Tags EN',
        'Tags CY',
        'Date',
        'Owner',
        'Creator',
        'Website en',
        'Website cy',
        'What facet',
        'When facet',
        'Location (lat, lon)',
        'Location description en',
        'Location description cy',
        'Right Type 1',
        'Right Holder 1 EN',
        'Right Holder 1 CY',
        'Begin Date 1',
        'Right Type 2',
        'Right Holder 2 EN',
        'Right Holder 2 CY',
        'Begin Date 2',
        'Right Type 3',
        'Right Holder 3 EN',
        'Right Holder 3 CY',
        'Begin Date 3',
        'Addional rights'
      )
    );    
  }


}